name: flutter_tailwind_theme
description: A Flutter package providing a comprehensive set of pre-defined Tailwind colors, fonts, sizes and ... for rapid UI development.
version: 1.0.2
homepage: https://github.com/nimahedayati/flutter_tailwind_theme

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: